import crypto from 'node:crypto';
import { pool } from '../pool.js';
function toCoupon(row){if(!row)return null;return{id:row.id,code:row.code,type:row.type,value:Number(row.value),minOrder:Number(row.min_order),maxUses:row.max_uses,usedCount:row.used_count,active:row.active,expiresAt:row.expires_at,createdAt:row.created_at};}
export async function listCoupons(){const{rows}=await pool.query('SELECT * FROM coupons ORDER BY created_at DESC');return rows.map(toCoupon);}
export async function getCouponByCode(code,client=pool){const{rows}=await client.query('SELECT * FROM coupons WHERE code=$1',[String(code||'').trim().toUpperCase()]);return toCoupon(rows[0]);}
export async function createCoupon(input){const{rows}=await pool.query(`INSERT INTO coupons(id,code,type,value,min_order,max_uses,active,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[crypto.randomUUID(),String(input.code).trim().toUpperCase(),input.type==='fixed'?'fixed':'percent',Number(input.value)||0,Number(input.minOrder)||0,input.maxUses===''||input.maxUses==null?null:Number(input.maxUses),input.active!==false,input.expiresAt?new Date(input.expiresAt):null]);return toCoupon(rows[0]);}
export async function updateCoupon(id,input){const e=await pool.query('SELECT * FROM coupons WHERE id=$1',[id]);if(!e.rows[0])return null;const c=e.rows[0];const{rows}=await pool.query(`UPDATE coupons SET code=$2,type=$3,value=$4,min_order=$5,max_uses=$6,active=$7,expires_at=$8 WHERE id=$1 RETURNING *`,[id,input.code!==undefined?String(input.code).trim().toUpperCase():c.code,input.type!==undefined?(input.type==='fixed'?'fixed':'percent'):c.type,input.value!==undefined?Number(input.value):c.value,input.minOrder!==undefined?Number(input.minOrder):c.min_order,input.maxUses!==undefined?(input.maxUses===''||input.maxUses==null?null:Number(input.maxUses)):c.max_uses,input.active!==undefined?Boolean(input.active):c.active,input.expiresAt!==undefined?(input.expiresAt?new Date(input.expiresAt):null):c.expires_at]);return toCoupon(rows[0]);}
export async function deleteCoupon(id){const{rowCount}=await pool.query('DELETE FROM coupons WHERE id=$1',[id]);return rowCount>0;}
export async function validateCoupon(code,subtotal,client=pool){const coupon=await getCouponByCode(code,client);if(!coupon)return{valid:false,reason:'Coupon code not found.'};if(!coupon.active)return{valid:false,reason:'This coupon is no longer active.'};if(coupon.expiresAt&&new Date(coupon.expiresAt).getTime()<Date.now())return{valid:false,reason:'This coupon has expired.'};if(coupon.maxUses!==null&&coupon.usedCount>=coupon.maxUses)return{valid:false,reason:'This coupon has reached its usage limit.'};if(subtotal<coupon.minOrder)return{valid:false,reason:`This coupon requires a minimum order of ${coupon.minOrder}.`};const discount=coupon.type==='fixed'?Math.min(coupon.value,subtotal):Math.round(subtotal*(coupon.value/100));return{valid:true,coupon,discount};}
export async function redeemCouponAtomically(code,orderId,userId,couponId,client=pool){const{rows}=await client.query(`UPDATE coupons SET used_count=used_count+1 WHERE id=$1 AND active=true AND (max_uses IS NULL OR used_count<max_uses) RETURNING *`,[couponId]);if(!rows[0])throw Object.assign(new Error('Coupon usage limit was reached. Please retry without the coupon.'),{status:409});await client.query('INSERT INTO coupon_redemptions(id,coupon_id,order_id,user_id) VALUES($1,$2,$3,$4)',[crypto.randomUUID(),couponId,orderId,userId]);return toCoupon(rows[0]);}
export async function countActiveCoupons(){const{rows}=await pool.query('SELECT COUNT(*)::int n FROM coupons WHERE active=true');return rows[0].n;}
