apiVersion: v1
kind: ServiceAccount
metadata:
  name: velora
  namespace: velora
  labels:
    helm.sh/chart: velora-1.0.0
    app.kubernetes.io/name: velora
    app.kubernetes.io/instance: velora
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
